### ISSUE TITLE
Cannot validate argument on parameter 'WslInstanceName'

### ISSUE THREAD

**Issue by hatakawas** [wikiped/Wsl-IpHandler#27]
When I follow the **Module Activation** section in README to  activate in static mode, I got this error.
My command: 
```
Install-WslIpHandler -WslInstanceName Ubuntu-20.04 -GatewayIpAddress 172.16.0.1
```
And the output:
```
Install-WslIpHandler: Cannot validate argument on parameter 'WslInstanceName'. Valid values generator return a null value.
```
![image](https://user-images.githubusercontent.com/7748560/175487129-ee5f4a0f-59d9-4482-9c49-002c6d8e8128.png)

Would you mind help me out there?
Thanks!

**Comment by wikiped** [comment]
This seems to be a duplicate of #25.

Could you please [update](https://github.com/wikiped/Wsl-IpHandler#how-to-update-this-module) to the latest version and try again?

**Comment by hatakawas** [comment]
As you see, I just reinstalled it minutes ago, and error kept there.
Just check my actions and the output:
```
PS C:\Users> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
PS C:\Users> [Console]::InputEncoding, [Console]::OutputEncoding | select -Exp EncodingName
Chinese Simplified (GB2312)
Chinese Simplified (GB2312)
PS C:\Users> wsl.exe --status
默认分发：Ubuntu-20.04
默认版本：2

适用于 Linux 的 Windows 子系统最后更新于 2022/6/16
WSL 自动更新启用。
Windows 更新已暂停。

内核版本： 5.10.16
PS C:\Users> ipmo Wsl-IpHandler -Force
PS C:\Users> . (join-path (split-path (gmo Wsl-IpHandler).Path) 'Scripts/Powershell/FunctionsArgumentCompleters.ps1')
PS C:\Users> wsl.exe -l | Convert-CommandOutput -SourceEncoding 'ibm850'
?u?N Linux ?v Windows P[1|?~RDSHr:


Ubuntu-20.04 (?×??)



PS C:\Users> wsl.exe -l | Convert-CommandOutput -DestinationEncoding 'ibm850'
?? Linux ???????? ?????:
Ubuntu-20.04 (?)
PS C:\Users> Install-WslIpHandler -WslInstanceName Ubuntu-20.04 -GatewayIpAddress 172.16.0.1
Install-WslIpHandler: Cannot validate argument on parameter 'WslInstanceName'. Valid values generator return a null value.
PS C:\Users> Install-WslIpHandler -WslInstanceName   Ubuntu-20.04 -GatewayIpAddress 172.16.0.1
Install-WslIpHandler: Cannot validate argument on parameter 'WslInstanceName'. Valid values generator return a null value.
PS C:\Users>
```
**But while i do this:**
```
ipmo Wsl-IpHandler; . (join-path (split-path (gmo Wsl-IpHandler).Path) 'Scripts/Powershell/FunctionsArgumentCompleters.ps1'); Get-WslInstancesNames
```
the console was flushed....
```
   at System.Management.Automation.PSModuleInfo.GetExportedTypeDefinitions()
   at System.Management.Automation.PSModuleInfo.GetExportedTypeDefinitions()
   at System.Management.Automation.AnalysisCache.CacheModuleExports(System.Management.Automation.PSModuleInfo, System.Management.Automation.ExecutionContext)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo, Boolean, System.Collections.Generic.IEnumerable`1<System.String>, System.String, System.Management.Automation.SessionState, ImportModuleOptions, ManifestProcessingFlags, System.Management.Automation.PSModuleInfo ByRef)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions, System.String)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   at System.Management.Automation.CommandProcessorBase.DoExecute()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.PipelineOps.InvokePipeline(System.Object, Boolean, System.Management.Automation.CommandParameterInternal[][], System.Management.Automation.Language.CommandBaseAst[], System.Management.Automation.CommandRedirection[][], System.Management.Automation.Language.FunctionContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.Interpreter.Run(System.Management.Automation.Interpreter.InterpretedFrame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(System.Action`1<System.Management.Automation.Language.FunctionContext>, System.Object, System.Object)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(System.Management.Automation.CommandProcessorBase)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.Thread+StartHelper.Callback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Thread.StartCallback()

[process exited with code 3221225725 (0xc00000fd)]
```
As you can see, the terminal is terminated...lol

I've uninstalled and reinstalled it before all the struglings above.

**Comment by hatakawas** [comment]
After checked the Beta UTF-8 option, the error disapeared.
![image](https://user-images.githubusercontent.com/7748560/175501088-3ef596df-c0a5-4121-9338-65b0b9ee7b96.png)
But get new error
![image](https://user-images.githubusercontent.com/7748560/175501258-ba1334e2-c442-4523-a189-9c5eb6a5d684.png)

**Comment by hatakawas** [comment]
Finally there!!!

Note here to help others:

1. Checked the Beta UTF-8 option in regin settings to solve the `Cannot validate argument on parameter 'WslInstanceName'` problem.

2. Removed the `$_` in the /path/to/Wsl-IpHandler/Scripts/Powershell/FunctionsHostsFile.ps1 Line265,  to solve the `null-valued expression` problem.

3. Execute below command with Administrator in powershell:
```
New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow
```
to add a filewall rule to solve the `PING-failed` problem.

Hope to help others. That's all.

**Comment by wikiped** [comment]
Thanks for sharing your findings.

However:

Last error that you showed regarding `Get-IpAddressHostsCommentTuple` failing when `$null` is passed was fixed in #28.
So removing `$_` from the source file as you suggested will mean that you have to manage your `hosts` file manually.

As far as I am aware normally (i.e. "out-of-the-box") WSL2 has no blocking inbound firewall rules so ping error at the end indicates exactly what it means - that there was a problem with installation - which is to be expected if hosts file was not edited properly.

**Comment by wikiped** [comment]
If you read the error you might notice that this is actually a different error, that was previously reported and fixed: #22

Can you show output of the following command:

```powershell
ipmo Wsl-IpHandler -Pass | gmo | select -exp Version
```

**Comment by hatakawas** [comment]
> 

![image](https://user-images.githubusercontent.com/7748560/190533617-473d0e1b-5c40-4b62-b701-1d21f740e035.png)

**Comment by wikiped** [comment]
So the [error](https://github.com/wikiped/Wsl-IpHandler/issues/27#issuecomment-1248022251) is gone, correct?

Can you post output of the following two commands:

```powershell
Get-WslStatus
Get-WslInstanceStatus -WslInstanceName Ubuntu-20.04
```

**Comment by hatakawas** [comment]
Sorry, I was very busy recent days. I will close this issue for now. 
Thanks for your help.
